### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by AppleMinerHD** [robske110/SignServerStats#1]
The Plugin disables my DevTools and i can't load it.

**Comment by robske110** [comment]
There is currently a WIP on version 1.0 on the master branch.
I'll quickly compile a phar from https://github.com/robske110/SignServerStats/commit/ee4dbae11334eff17dfc0b843610345a1d822885 for you, the last working version

**Comment by robske110** [comment]
and I may move the work away from master

**Comment by majovec** [comment]
Please update :(

**Comment by robske110** [comment]
https://github.com/robske110/SignServerStats/releases/tag/0.9.1
download the old, but working version there
https://github.com/robske110/SignServerStats/releases/download/0.9.1/SignServerStats_v0.9.1.phar (direct link)

**Comment by majovec** [comment]
thanks

**Comment by majovec** [comment]
Robske i need help why not load count  synapse server on  and sign is offline  synapse server off sign si online

**Comment by robske110** [comment]
you need to enter the direct IP&port of your real server. not the synapse server.
