### ISSUE TITLE
Dependencies 

### ISSUE THREAD

**Issue by xDanub** [robske110/SignServerStats#9]
Plugin depends on SignServerStats, but when I installed SSS, the plugin still wouldn't enable, for the same reason.

**Comment by robske110** [comment]
Are you sure you installed SSS correctly, and with the current version from https://poggit.pmmp.io/p/SignServerStats/1.1.1 ? Please post your console output too.

**Comment by xDanub** [comment]
I installed both correctly, I also uninstalled and installed `3056e26a` and that fixed the issue. The server output was the default dependency error. ¯\_(ツ)_/¯ Kinda too lazy to go get it, but you can close the issue if you want
